name: Sandy
personal_project: Planning App
repo_names:
  - PlanningApp

# Provide assignment video URLs
10-ux-ui-criticism:
  - https://drive.google.com/file/d/1y4i-6c8vp_MTdvTUwAdZwzSGsCUFckZE/view?usp=sharing
  - https://drive.google.com/file/d/1aqpVCHbxrRr_cY4dypoWiIV1RYlHNqHY/view?usp=sharing
  
11-models-from-data: https://github.com/sl30724/PlanningApp/blob/main/Planning/Views/TaskCard.swift
  
project-check-in-1: https://github.com/sl30724/PlanningApp/issues/2#issue-1424668261
